# Generated by Django 3.0.8 on 2020-11-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
