# Generated by Django 3.0.8 on 2020-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemegen', '0002_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemegen',
            name='type',
            field=models.CharField(choices=[("Women's Development", "Women's Development"), ('Social Justice', 'Social Justice'), ('Sports', 'Sports'), ('Ruler Development', 'Ruler Development'), ('Child Development', 'Child Development')], default="Women's Development", max_length=20),
        ),
    ]
